Restructure script

diff --git a/bashenv b/bashenv
--- a/bashenv
+++ b/bashenv
@@ -4,50 +4,50 @@
 # make this script callable from anywhere!
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 flag=
-
-if [ -f $1 ]
-then
-	# loop through and export the file as needed
-	# remove all comments and empty lines before hand
-	awk 'NF' $1 | grep -v \# | while read line 
-	do
-		# check for a script include primitive
-		if [[ $line =~ include* ]]
-		then
-			# if so then recursively call with the correct file
-			file=`echo $line | awk '{ split($0, a, " "); print a[2] }'`
-
-			# try to load the include directive
-			if [[ (-n $file) && -f $file  ]]
-			then
-				# recursively load this file
-				\. $0 $file
-			else
-				# print message 
-				echo "Include not found for: $file" 
-			fi
-		# check for a block primitive
-		elif [[ "$line" =~ '^\[.*\]$' ]];then
-		  # check if end of flag
-      if [[ "$(echo $line | awk '{ print tolower($0) }')" = "[end]" ]];then
-        flag=
-      # start of block, evaluate accordingly
-      else
-        # evaluate line and see if the comman is true
-        eval $line
-        # check return status, 0 is true
-        if [[ $? -eq 0 ]];then
-          flag="true"
-        else
-          flag="false"
-        fi
-      fi
-		# evaluate lines 
-		else
-      if [[ $flag == "" || $flag == "true" ]];then
-        eval "export $line"
-      fi
-		fi
-	done
+if [[ ! -f $1 ]];then
+  exit 1
 fi
+
+# loop through and export the file as needed
+# remove all comments and empty lines before hand
+awk 'NF' $1 | grep -v \# | while read line 
+do
+  # check for a script include primitive
+  if [[ $line =~ include* ]]
+  then
+    # if so then recursively call with the correct file
+    file=`echo $line | awk '{ split($0, a, " "); print a[2] }'`
+
+    # try to load the include directive
+    if [[ (-n $file) && -f $file  ]]
+    then
+      # recursively load this file
+      \. $0 $file
+    else
+      # print message 
+      echo "Include not found for: $file" 
+    fi
+  # check for a block primitive
+  elif [[ "$line" =~ '^\[.*\]$' ]];then
+    # check if end of flag
+    if [[ "$(echo $line | awk '{ print tolower($0) }')" = "[end]" ]];then
+      flag=
+    # start of block, evaluate accordingly
+    else
+      # evaluate line and see if the comman is true
+      eval $line
+      # check return status, 0 is true
+      if [[ $? -eq 0 ]];then
+        flag="true"
+      else
+        flag="false"
+      fi
+    fi
+  # evaluate lines 
+  else
+    if [[ $flag == "" || $flag == "true" ]];then
+      eval "export $line"
+    fi
+  fi
+done
 
